name: CMake on a single platform

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15-intel

    steps:
    - uses: actions/checkout@v4

    - name: Remove macOS 14 SDK
      run: |
        sudo rm -rf /Library/Developer/CommandLineTools/SDKs/MacOSX14{,.5}.sdk

    - name: Install minizip-ng
      run: |
        brew install minizip-ng
        fgrep set_target_properties -A4 "$(brew --prefix minizip-ng)/lib/cmake/minizip-ng/minizip-ng.cmake"

    - name: Configure CMake
      run: |
        xcode-select -p
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Debug

    - name: Build
      run: cmake --build build -- -v
