name: CMake on a single platform

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      run: |
        cat "$(brew --prefix minizip-ng)/lib/cmake/minizip-ng/minizip-ng.cmake"
        xcode-select -p
        brew install minizip-ng
        cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build -- -v
